module.exports = {
    auth_required: [
        '/user/setUserInfo',
        '/user/getUserInfo',
        '/user/addContacts',
        '/user/addSms',
        '/user/addInstalledApplications',
        '/user/updateLocation',
        '/loan/createLoan',
        '/loan/getLoanSettings',
        '/loan/payLoan',
        '/loan/getUserLoans',
        '/loan/getUserLoan',
    ],

    routes: [
        '/auth/signPhone',
        '/auth/signCode',
        '/auth/refreshToken',
        '/user/setUserInfo',
        '/user/getUserInfo',
        '/user/addContacts',
        '/user/addSms',
        '/user/addInstalledApplications',
        '/user/updateLocation',
        '/loan/createLoan',
        '/loan/getLoanSettings',
        '/loan/payLoan',
        '/loan/getUserLoans',
        '/loan/getUserLoan',
    ],
};
